# Generated by Django 3.1.2 on 2020-11-25 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default=datetime.datetime(2020, 11, 25, 21, 30, 58, 27556), max_length=255, verbose_name='Имя'),
        ),
    ]
